language: node_js
node_js: 0.10
notifications:
  email: false
env: 
  global: 
    - GIT_AUTHOR_NAME=t32k
    - GIT_AUTHOR_EMAIL=ijok.ijok@gmail.com
    - GIT_COMMITTER_NAME=t32k
    - GIT_COMMITTER_EMAIL=ijok.ijok@gmail.com
    - secure: UuE3YYrTD4KOz+XinOVq5LIFxfFp/6d2IxuWTEg3SqJWvjUhTZgFWQEQDU4+GWsi9nk+ww9wcjDsuJX7Ia8QDuI01mPIkwhllTxwYvSjDbnzxL6g4xkVK0wU2Dr1SdLuIDqMeq/wz6QomUjK7QRatAm3DUNMSsWDAB3ngTTZJoM=

script: 
  - "git clone --quiet https://github.com/t32k/maple.git"
  - "git checkout -b gh-pages"
  - "git rebase master"
  - "[ \"$TRAVIS_BRANCH\" == \"master\" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/t32k/maple.git gh-pages 2> /dev/null"
